### ISSUE TITLE
Uncaught type error when loading quotes.js

### ISSUE THREAD

**Issue by i001962** [jamesmosier/stock-movers#1]
After fresh install and npm run dev the initial page loads correctly but when quotes link is selected an error is thrown.

Uncaught TypeError: Cannot read property 'state' of undefined
    at quotes.js:204
    at Array.map (<anonymous>)
    at ProxyComponent.render (quotes.js:202)

Cannot read property 'state' of undefined
TypeError: Cannot read property 'state' of undefined
    at http://localhost:4444/_next/-/page/quotes.js:17158:67
    at Array.map (<anonymous>)
    at ProxyComponent.render (pages/quotes.js:202:0)

Probably unrealated but I was wondering why you are calling https://api.iextrading.com/1.0/stock/market/list/mostactive from index.js but iex from quotes to retrieve them most active.

Nice project! You've provided a handy example for calling iextrading api

**Comment by jamesmosier** [comment]
Wow I have no idea how I missed your comment @i001962. Sorry about the extreme delay!

I just added a fix for the error you were seeing. It looks like the newest version of `next.js` was not working as I expected.

As far as your question, are you wondering why I call the robinhood API from `index.js` but iex from the `quotes` page? If so, the reason was just to get some different data samples from different sources. 

And thank you! I'm glad you found the project useful.
